/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import FramesPanels.AddDriver;
import FramesPanels.RemoveDriver;
import FramesPanels.SearchDriver;
import FramesPanels.UpdateDriver;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author dell
 */
public class DriverFrame extends javax.swing.JFrame {
    private final AddDriver p1;
    private final SearchDriver p2;
    private final RemoveDriver p3;
    private final UpdateDriver p4;
    GridBagLayout layout = new GridBagLayout();
    
            
    

    /**
     * Creates new form DriverFrame
     */
    public DriverFrame() {
        initComponents();
        p1 = new AddDriver();
        p2 = new SearchDriver();
        p3 = new RemoveDriver();
        p4 = new UpdateDriver();
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p1);
        DynamicPanel.add(p2);
        DynamicPanel.add(p3);
        DynamicPanel.add(p4);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg4 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        UpdateDriver = new javax.swing.JPanel();
        UpdateLogo = new javax.swing.JLabel();
        TextUpdate = new javax.swing.JLabel();
        AddDriver = new javax.swing.JPanel();
        AddLogo = new javax.swing.JLabel();
        TextAdd = new javax.swing.JLabel();
        SearchDriver = new javax.swing.JPanel();
        SearchLogo = new javax.swing.JLabel();
        TextSearch = new javax.swing.JLabel();
        DeleteDriver = new javax.swing.JPanel();
        RemoveLogo = new javax.swing.JLabel();
        TextRemove = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));

        UpdateDriver.setBackground(new java.awt.Color(64, 43, 100));
        UpdateDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateDriverMouseClicked(evt);
            }
        });

        UpdateLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpdateLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Refresh_52px_4.png"))); // NOI18N

        TextUpdate.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextUpdate.setForeground(new java.awt.Color(255, 255, 255));
        TextUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextUpdate.setText("Update Driver");
        TextUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextUpdateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UpdateDriverLayout = new javax.swing.GroupLayout(UpdateDriver);
        UpdateDriver.setLayout(UpdateDriverLayout);
        UpdateDriverLayout.setHorizontalGroup(
            UpdateDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDriverLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(UpdateLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(TextUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdateDriverLayout.setVerticalGroup(
            UpdateDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdateDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDriverLayout.createSequentialGroup()
                        .addComponent(UpdateLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(UpdateDriverLayout.createSequentialGroup()
                        .addComponent(TextUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(23, 23, 23))))
        );

        AddDriver.setBackground(new java.awt.Color(64, 43, 100));
        AddDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddDriverMouseClicked(evt);
            }
        });

        AddLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Driver_50px.png"))); // NOI18N

        TextAdd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextAdd.setForeground(new java.awt.Color(255, 255, 255));
        TextAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextAdd.setText("Add Driver");
        TextAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddDriverLayout = new javax.swing.GroupLayout(AddDriver);
        AddDriver.setLayout(AddDriverLayout);
        AddDriverLayout.setHorizontalGroup(
            AddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDriverLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AddLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(TextAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddDriverLayout.setVerticalGroup(
            AddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SearchDriver.setBackground(new java.awt.Color(64, 43, 100));
        SearchDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchDriverMouseClicked(evt);
            }
        });

        SearchLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_50px_3.png"))); // NOI18N

        TextSearch.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextSearch.setForeground(new java.awt.Color(255, 255, 255));
        TextSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSearch.setText("Search Driver");
        TextSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SearchDriverLayout = new javax.swing.GroupLayout(SearchDriver);
        SearchDriver.setLayout(SearchDriverLayout);
        SearchDriverLayout.setHorizontalGroup(
            SearchDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchDriverLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(SearchLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchDriverLayout.setVerticalGroup(
            SearchDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SearchDriverLayout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        DeleteDriver.setBackground(new java.awt.Color(64, 43, 100));
        DeleteDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteDriverMouseClicked(evt);
            }
        });

        RemoveLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemoveLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trash_Can_50px.png"))); // NOI18N

        TextRemove.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextRemove.setForeground(new java.awt.Color(255, 255, 255));
        TextRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRemove.setText("Remove Driver");
        TextRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DeleteDriverLayout = new javax.swing.GroupLayout(DeleteDriver);
        DeleteDriver.setLayout(DeleteDriverLayout);
        DeleteDriverLayout.setHorizontalGroup(
            DeleteDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDriverLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(RemoveLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(TextRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        DeleteDriverLayout.setVerticalGroup(
            DeleteDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeleteDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteDriverLayout.createSequentialGroup()
                        .addComponent(RemoveLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteDriverLayout.createSequentialGroup()
                        .addComponent(TextRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_50px.png"))); // NOI18N

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SearchDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UpdateDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DeleteDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(AddDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(SearchDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(DeleteDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(UpdateDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        bg4.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 780));

        DynamicPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        bg4.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 2, 970, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDriverMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_AddDriverMouseClicked

    private void TextAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextAddMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_TextAddMouseClicked

    private void SearchDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchDriverMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_SearchDriverMouseClicked

    private void TextSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSearchMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_TextSearchMouseClicked

    private void DeleteDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteDriverMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
    }//GEN-LAST:event_DeleteDriverMouseClicked

    private void TextRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextRemoveMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
    }//GEN-LAST:event_TextRemoveMouseClicked

    private void UpdateDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDriverMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
    }//GEN-LAST:event_UpdateDriverMouseClicked

    private void TextUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextUpdateMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
    }//GEN-LAST:event_TextUpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDriver;
    private javax.swing.JLabel AddLogo;
    private javax.swing.JLabel Back;
    private javax.swing.JPanel DeleteDriver;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JLabel RemoveLogo;
    private javax.swing.JPanel SearchDriver;
    private javax.swing.JLabel SearchLogo;
    private javax.swing.JLabel TextAdd;
    private javax.swing.JLabel TextRemove;
    private javax.swing.JLabel TextSearch;
    private javax.swing.JLabel TextUpdate;
    private javax.swing.JPanel UpdateDriver;
    private javax.swing.JLabel UpdateLogo;
    private javax.swing.JPanel bg4;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
