/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import FramesPanels.AddPayments;
import FramesPanels.ShowTotalReciept;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author dell
 */
public class Payments extends javax.swing.JFrame {
    private final AddPayments p1;
    private final ShowTotalReciept p2;
    GridBagLayout layout = new GridBagLayout();

    /**
     * Creates new form Payments
     */
    public Payments() {
        initComponents();
        p1= new AddPayments();
        p2= new ShowTotalReciept();
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p1);
        DynamicPanel.add(p2);
        p1.setVisible(true);
        p2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg5 = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        AddPayments = new javax.swing.JPanel();
        AddPaymentLogo = new javax.swing.JLabel();
        TextAdd = new javax.swing.JLabel();
        ShowPayments = new javax.swing.JPanel();
        ShowLogo = new javax.swing.JLabel();
        TextShow = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(54, 33, 89));

        AddPayments.setBackground(new java.awt.Color(64, 43, 100));
        AddPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPaymentsMouseClicked(evt);
            }
        });

        AddPaymentLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddPaymentLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Money_50px_1.png"))); // NOI18N
        AddPaymentLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPaymentLogoMouseClicked(evt);
            }
        });

        TextAdd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextAdd.setForeground(new java.awt.Color(255, 255, 255));
        TextAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextAdd.setText("Add Payments");
        TextAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddPaymentsLayout = new javax.swing.GroupLayout(AddPayments);
        AddPayments.setLayout(AddPaymentsLayout);
        AddPaymentsLayout.setHorizontalGroup(
            AddPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPaymentsLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AddPaymentLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(TextAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddPaymentsLayout.setVerticalGroup(
            AddPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddPaymentLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(AddPaymentsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TextAdd)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        ShowPayments.setBackground(new java.awt.Color(64, 43, 100));
        ShowPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPaymentsMouseClicked(evt);
            }
        });

        ShowLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShowLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_TV_Show_50px.png"))); // NOI18N
        ShowLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowLogoMouseClicked(evt);
            }
        });

        TextShow.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextShow.setForeground(new java.awt.Color(255, 255, 255));
        TextShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextShow.setText("Show Total Reciept");
        TextShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ShowPaymentsLayout = new javax.swing.GroupLayout(ShowPayments);
        ShowPayments.setLayout(ShowPaymentsLayout);
        ShowPaymentsLayout.setHorizontalGroup(
            ShowPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPaymentsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ShowLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(TextShow)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        ShowPaymentsLayout.setVerticalGroup(
            ShowPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShowLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShowPaymentsLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(TextShow)
                .addGap(22, 22, 22))
        );

        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_50px.png"))); // NOI18N

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ShowPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(AddPayments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(ShowPayments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        bg5.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg5.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 0, -1, 852));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPaymentLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPaymentLogoMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_AddPaymentLogoMouseClicked

    private void AddPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPaymentsMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_AddPaymentsMouseClicked

    private void TextAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextAddMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_TextAddMouseClicked

    private void ShowLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowLogoMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_ShowLogoMouseClicked

    private void TextShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextShowMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_TextShowMouseClicked

    private void ShowPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPaymentsMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_ShowPaymentsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddPaymentLogo;
    private javax.swing.JPanel AddPayments;
    private javax.swing.JLabel Back;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JLabel ShowLogo;
    private javax.swing.JPanel ShowPayments;
    private javax.swing.JLabel TextAdd;
    private javax.swing.JLabel TextShow;
    private javax.swing.JPanel bg5;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
