/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import FramesPanels.AddVehicle;
import FramesPanels.CheckDamage;
import FramesPanels.SearchVehicle;
import FramesPanels.UpdateDelete;
import FramesPanels.ViewVehicle;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author dell
 */
public class VehicleFrame extends javax.swing.JFrame {
    private final AddVehicle p1;
    private final SearchVehicle p2;
    private final UpdateDelete p3;
    private final CheckDamage p4;
    private final ViewVehicle p5;
    GridBagLayout layout = new GridBagLayout();
    

    
    public VehicleFrame() {
        initComponents();
        p1= new AddVehicle();
        p2= new SearchVehicle();
        p3= new UpdateDelete();
        p4= new CheckDamage();
        p5= new ViewVehicle();
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p1);
        DynamicPanel.add(p2);
        DynamicPanel.add(p3);
        DynamicPanel.add(p4);
        DynamicPanel.add(p5);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg3 = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        ViewVehicle = new javax.swing.JPanel();
        ViewLogo = new javax.swing.JLabel();
        TextView = new javax.swing.JLabel();
        AddVehicle = new javax.swing.JPanel();
        AddLogo = new javax.swing.JLabel();
        TextAdd = new javax.swing.JLabel();
        SearchVehicle = new javax.swing.JPanel();
        SearchLogo = new javax.swing.JLabel();
        TextSearch = new javax.swing.JLabel();
        UpdateDelete = new javax.swing.JPanel();
        DeleteLogo = new javax.swing.JLabel();
        TextUpDelete = new javax.swing.JLabel();
        CheckDamage = new javax.swing.JPanel();
        DamageLogo = new javax.swing.JLabel();
        TextCheck = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg3.setBackground(new java.awt.Color(255, 255, 255));
        bg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(54, 33, 89));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewVehicle.setBackground(new java.awt.Color(64, 43, 100));
        ViewVehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewVehicleMouseClicked(evt);
            }
        });

        ViewLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_View_50px.png"))); // NOI18N

        TextView.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextView.setForeground(new java.awt.Color(255, 255, 255));
        TextView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextView.setText("View Vehicle");
        TextView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ViewVehicleLayout = new javax.swing.GroupLayout(ViewVehicle);
        ViewVehicle.setLayout(ViewVehicleLayout);
        ViewVehicleLayout.setHorizontalGroup(
            ViewVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewVehicleLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ViewLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextView, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewVehicleLayout.setVerticalGroup(
            ViewVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewVehicleLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TextView)
                .addContainerGap())
        );

        sidepanel.add(ViewVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 460, 80));

        AddVehicle.setBackground(new java.awt.Color(64, 43, 100));
        AddVehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddVehicleMouseClicked(evt);
            }
        });

        AddLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Convertible_64px.png"))); // NOI18N

        TextAdd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextAdd.setForeground(new java.awt.Color(255, 255, 255));
        TextAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextAdd.setText("Add Vehicle");
        TextAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextAddMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextAddMousePressed(evt);
            }
        });

        javax.swing.GroupLayout AddVehicleLayout = new javax.swing.GroupLayout(AddVehicle);
        AddVehicle.setLayout(AddVehicleLayout);
        AddVehicleLayout.setHorizontalGroup(
            AddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddVehicleLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(AddLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(TextAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddVehicleLayout.setVerticalGroup(
            AddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddVehicleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextAdd)
                .addContainerGap())
        );

        sidepanel.add(AddVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 460, 80));

        SearchVehicle.setBackground(new java.awt.Color(64, 43, 100));
        SearchVehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchVehicleMouseClicked(evt);
            }
        });

        SearchLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_50px_3.png"))); // NOI18N

        TextSearch.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextSearch.setForeground(new java.awt.Color(255, 255, 255));
        TextSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSearch.setText("Search Vehicle");
        TextSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SearchVehicleLayout = new javax.swing.GroupLayout(SearchVehicle);
        SearchVehicle.setLayout(SearchVehicleLayout);
        SearchVehicleLayout.setHorizontalGroup(
            SearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchVehicleLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(SearchLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchVehicleLayout.setVerticalGroup(
            SearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchVehicleLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TextSearch)
                .addContainerGap())
        );

        sidepanel.add(SearchVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 460, 80));

        UpdateDelete.setBackground(new java.awt.Color(64, 43, 100));
        UpdateDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateDeleteMouseClicked(evt);
            }
        });

        DeleteLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeleteLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trash_Can_50px.png"))); // NOI18N

        TextUpDelete.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextUpDelete.setForeground(new java.awt.Color(255, 255, 255));
        TextUpDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextUpDelete.setText("Update / Delete");
        TextUpDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextUpDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextUpDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UpdateDeleteLayout = new javax.swing.GroupLayout(UpdateDelete);
        UpdateDelete.setLayout(UpdateDeleteLayout);
        UpdateDeleteLayout.setHorizontalGroup(
            UpdateDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeleteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(DeleteLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextUpDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdateDeleteLayout.setVerticalGroup(
            UpdateDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeleteLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDeleteLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TextUpDelete)
                .addContainerGap())
        );

        sidepanel.add(UpdateDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 460, 80));

        CheckDamage.setBackground(new java.awt.Color(64, 43, 100));
        CheckDamage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckDamage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckDamageMouseClicked(evt);
            }
        });

        DamageLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DamageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Crashed_Car_50px.png"))); // NOI18N

        TextCheck.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TextCheck.setForeground(new java.awt.Color(255, 255, 255));
        TextCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextCheck.setText("Check Damage");
        TextCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextCheckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CheckDamageLayout = new javax.swing.GroupLayout(CheckDamage);
        CheckDamage.setLayout(CheckDamageLayout);
        CheckDamageLayout.setHorizontalGroup(
            CheckDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckDamageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(DamageLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckDamageLayout.setVerticalGroup(
            CheckDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DamageLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckDamageLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TextCheck)
                .addContainerGap())
        );

        sidepanel.add(CheckDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 460, 80));

        Back.setBackground(new java.awt.Color(54, 33, 89));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_50px.png"))); // NOI18N
        sidepanel.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        bg3.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 980));

        DynamicPanel.setBackground(new java.awt.Color(255, 255, 255));
        DynamicPanel.setPreferredSize(new java.awt.Dimension(1092, 876));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        bg3.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 950, 980));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextAddMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAddMousePressed

    private void TextAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextAddMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        
    }//GEN-LAST:event_TextAddMouseClicked

    private void TextSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSearchMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_TextSearchMouseClicked

    private void AddVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddVehicleMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_AddVehicleMouseClicked

    private void SearchVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchVehicleMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_SearchVehicleMouseClicked

    private void UpdateDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDeleteMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_UpdateDeleteMouseClicked

    private void CheckDamageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckDamageMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
    }//GEN-LAST:event_CheckDamageMouseClicked

    private void ViewVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewVehicleMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
    }//GEN-LAST:event_ViewVehicleMouseClicked

    private void TextUpDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextUpDeleteMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_TextUpDeleteMouseClicked

    private void TextCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextCheckMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
    }//GEN-LAST:event_TextCheckMouseClicked

    private void TextViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextViewMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
    }//GEN-LAST:event_TextViewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLogo;
    private javax.swing.JPanel AddVehicle;
    private javax.swing.JLabel Back;
    private javax.swing.JPanel CheckDamage;
    private javax.swing.JLabel DamageLogo;
    private javax.swing.JLabel DeleteLogo;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JLabel SearchLogo;
    private javax.swing.JPanel SearchVehicle;
    private javax.swing.JLabel TextAdd;
    private javax.swing.JLabel TextCheck;
    private javax.swing.JLabel TextSearch;
    private javax.swing.JLabel TextUpDelete;
    private javax.swing.JLabel TextView;
    private javax.swing.JPanel UpdateDelete;
    private javax.swing.JLabel ViewLogo;
    private javax.swing.JPanel ViewVehicle;
    private javax.swing.JPanel bg3;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
