/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author dell
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg2 = new javax.swing.JPanel();
        employeepanel = new javax.swing.JPanel();
        jLabelEmployeeLogo = new javax.swing.JLabel();
        jLabelEmloyeeText = new javax.swing.JLabel();
        driver = new javax.swing.JPanel();
        jLabelDriverLogo = new javax.swing.JLabel();
        jLabelDriverText = new javax.swing.JLabel();
        vehicle = new javax.swing.JPanel();
        jLabelVehicleLogo = new javax.swing.JLabel();
        jLabelVehicleText = new javax.swing.JLabel();
        customer = new javax.swing.JPanel();
        jLabelCustomerLogo = new javax.swing.JLabel();
        jLabelCustomerText = new javax.swing.JLabel();
        payments = new javax.swing.JPanel();
        jLabelPaymentsLogo = new javax.swing.JLabel();
        jLabelPaymentsText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setLocationByPlatform(true);
        setUndecorated(true);

        bg2.setBackground(new java.awt.Color(54, 33, 89));

        employeepanel.setBackground(new java.awt.Color(64, 43, 100));

        jLabelEmployeeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmployeeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Employee_50px.png"))); // NOI18N

        jLabelEmloyeeText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelEmloyeeText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmloyeeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmloyeeText.setText("Employee");

        javax.swing.GroupLayout employeepanelLayout = new javax.swing.GroupLayout(employeepanel);
        employeepanel.setLayout(employeepanelLayout);
        employeepanelLayout.setHorizontalGroup(
            employeepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEmployeeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmloyeeText)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        employeepanelLayout.setVerticalGroup(
            employeepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEmployeeLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeepanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabelEmloyeeText)
                .addGap(25, 25, 25))
        );

        driver.setBackground(new java.awt.Color(64, 43, 100));

        jLabelDriverLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDriverLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Driver_50px.png"))); // NOI18N

        jLabelDriverText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelDriverText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDriverText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDriverText.setText("Driver");

        javax.swing.GroupLayout driverLayout = new javax.swing.GroupLayout(driver);
        driver.setLayout(driverLayout);
        driverLayout.setHorizontalGroup(
            driverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDriverLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelDriverText, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        driverLayout.setVerticalGroup(
            driverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDriverLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDriverText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        vehicle.setBackground(new java.awt.Color(64, 43, 100));

        jLabelVehicleLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVehicleLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Convertible_64px.png"))); // NOI18N

        jLabelVehicleText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelVehicleText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVehicleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVehicleText.setText("Vehicle");

        javax.swing.GroupLayout vehicleLayout = new javax.swing.GroupLayout(vehicle);
        vehicle.setLayout(vehicleLayout);
        vehicleLayout.setHorizontalGroup(
            vehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelVehicleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabelVehicleText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        vehicleLayout.setVerticalGroup(
            vehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVehicleLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehicleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelVehicleText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        customer.setBackground(new java.awt.Color(64, 43, 100));

        jLabelCustomerLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Customer_50px_1.png"))); // NOI18N

        jLabelCustomerText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCustomerText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCustomerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerText.setText("Customer");

        javax.swing.GroupLayout customerLayout = new javax.swing.GroupLayout(customer);
        customer.setLayout(customerLayout);
        customerLayout.setHorizontalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelCustomerLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabelCustomerText, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        customerLayout.setVerticalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCustomerLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabelCustomerText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        payments.setBackground(new java.awt.Color(64, 43, 100));

        jLabelPaymentsLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaymentsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Money_50px_1.png"))); // NOI18N

        jLabelPaymentsText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelPaymentsText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaymentsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaymentsText.setText("Payments");

        javax.swing.GroupLayout paymentsLayout = new javax.swing.GroupLayout(payments);
        payments.setLayout(paymentsLayout);
        paymentsLayout.setHorizontalGroup(
            paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelPaymentsLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabelPaymentsText)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        paymentsLayout.setVerticalGroup(
            paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelPaymentsText)
                .addGap(29, 29, 29))
            .addGroup(paymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaymentsLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(employeepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(payments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(vehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(159, 159, 159)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg2;
    private javax.swing.JPanel customer;
    private javax.swing.JPanel driver;
    private javax.swing.JPanel employeepanel;
    private javax.swing.JLabel jLabelCustomerLogo;
    private javax.swing.JLabel jLabelCustomerText;
    private javax.swing.JLabel jLabelDriverLogo;
    private javax.swing.JLabel jLabelDriverText;
    private javax.swing.JLabel jLabelEmloyeeText;
    private javax.swing.JLabel jLabelEmployeeLogo;
    private javax.swing.JLabel jLabelPaymentsLogo;
    private javax.swing.JLabel jLabelPaymentsText;
    private javax.swing.JLabel jLabelVehicleLogo;
    private javax.swing.JLabel jLabelVehicleText;
    private javax.swing.JPanel payments;
    private javax.swing.JPanel vehicle;
    // End of variables declaration//GEN-END:variables
}
