/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

import pl.pro.Driver;

/**
 *
 * @author dell
 */
public class AddDriver extends javax.swing.JPanel {

    /**
     * Creates new form AddDriver
     */
    public AddDriver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simplePanel = new javax.swing.JPanel();
        jLabelAddD = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelExper = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jLabelCo_B = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldGender = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldExper = new javax.swing.JTextField();
        jTextFieldPhoto = new javax.swing.JTextField();
        jTextFieldCo_B = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        succes = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        simplePanel.setBackground(new java.awt.Color(54, 33, 89));

        jLabelAddD.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelAddD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAddD.setText("Add Driver");

        javax.swing.GroupLayout simplePanelLayout = new javax.swing.GroupLayout(simplePanel);
        simplePanel.setLayout(simplePanelLayout);
        simplePanelLayout.setHorizontalGroup(
            simplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simplePanelLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabelAddD, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        simplePanelLayout.setVerticalGroup(
            simplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simplePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAddD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(54, 33, 89));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name");

        jLabelGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(54, 33, 89));
        jLabelGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGender.setText("Gender");

        jLabelPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPhone.setForeground(new java.awt.Color(54, 33, 89));
        jLabelPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPhone.setText("Phone_NO");

        jLabelAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(54, 33, 89));
        jLabelAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAddress.setText("Address");

        jLabelExper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelExper.setForeground(new java.awt.Color(54, 33, 89));
        jLabelExper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExper.setText("Experience");

        jLabelPhoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPhoto.setForeground(new java.awt.Color(54, 33, 89));
        jLabelPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPhoto.setText("Photo");

        jLabelCo_B.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCo_B.setForeground(new java.awt.Color(54, 33, 89));
        jLabelCo_B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCo_B.setText("Company Brande");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhotoActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(54, 33, 89));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_50px.png"))); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simplePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCo_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelExper, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(jLabelGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldGender)
                            .addComponent(jTextFieldPhone)
                            .addComponent(jTextFieldAddress)
                            .addComponent(jTextFieldExper)
                            .addComponent(jTextFieldPhoto)
                            .addComponent(jTextFieldCo_B, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(succes, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(simplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGender)
                    .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExper, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldExper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCo_B)
                    .addComponent(jTextFieldCo_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(succes))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhotoActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldName.getText().equals("")&&!jTextFieldGender.getText().equals("")&&!jTextFieldPhone.getText().equals("")&&!jTextFieldAddress.getText().equals("")&&!jTextFieldExper.getText().equals("")&&!jTextFieldPhoto.getText().equals("")&&!jTextFieldCo_B.getText().equals("")){
            Driver x= new Driver();
            x.setName(jTextFieldName.getText());
            x.setGender(jTextFieldGender.getText());
            x.setPhone_no(jTextFieldPhone.getText());
            x.setAddress(jTextFieldAddress.getText());
            x.setExperience(jTextFieldExper.getText());
            x.setPhoto(jTextFieldPhoto.getText());
            x.setCompany_brand(jTextFieldCo_B.getText());
            if(x.AddDriver()){
                succes.setText("Added Succesfully ..");
                resetPanelData();
            }else{
                succes.setText("Failed To Insert ..");
            }
        }else{
            succes.setText("Missing Required Fields ..! Please , Complete them before Submit ");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    protected void resetPanelData(){
        jTextFieldName.setText("");
        jTextFieldGender.setText("");
        jTextFieldPhone.setText("");
        jTextFieldAddress.setText("");
        jTextFieldExper.setText("");
        jTextFieldPhoto.setText("");
        jTextFieldCo_B.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabelAddD;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCo_B;
    private javax.swing.JLabel jLabelExper;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCo_B;
    private javax.swing.JTextField jTextFieldExper;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPhoto;
    private javax.swing.JPanel simplePanel;
    private javax.swing.JTextField succes;
    // End of variables declaration//GEN-END:variables
}
