/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

import pl.pro.Vehicle;

/**
 *
 * @author dell
 */
public class UpdateDelete extends javax.swing.JPanel {

    /**
     * Creates new form UpdateDelete
     */
    public UpdateDelete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simplepanel = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        jTextUpdateDelete = new javax.swing.JTextField();
        jButtonSearchU = new javax.swing.JButton();
        variantT = new javax.swing.JLabel();
        Co_Brande = new javax.swing.JLabel();
        jTextFieldIngine = new javax.swing.JTextField();
        rentVT = new javax.swing.JLabel();
        jTextFieldType = new javax.swing.JTextField();
        jTextFieldCO = new javax.swing.JTextField();
        jTextFieldVariant = new javax.swing.JTextField();
        jTextFieldUse = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jTextFieldRentV = new javax.swing.JTextField();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldNum = new javax.swing.JTextField();
        useasT = new javax.swing.JLabel();
        jTextFieldMYear = new javax.swing.JTextField();
        statusT = new javax.swing.JLabel();
        jTextFieldSitting = new javax.swing.JTextField();
        modelT = new javax.swing.JLabel();
        numberT = new javax.swing.JLabel();
        makeyearT = new javax.swing.JLabel();
        sittingCT = new javax.swing.JLabel();
        ingineCT = new javax.swing.JLabel();
        typeT = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        succes = new javax.swing.JLabel();
        jLabelFNot = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        simplepanel.setBackground(new java.awt.Color(54, 33, 89));

        Add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add.setText("Update/Delete A Vehicle");

        javax.swing.GroupLayout simplepanelLayout = new javax.swing.GroupLayout(simplepanel);
        simplepanel.setLayout(simplepanelLayout);
        simplepanelLayout.setHorizontalGroup(
            simplepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simplepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add)
                .addGap(380, 380, 380))
        );
        simplepanelLayout.setVerticalGroup(
            simplepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simplepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add)
                .addContainerGap())
        );

        jTextUpdateDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonSearchU.setBackground(new java.awt.Color(54, 33, 89));
        jButtonSearchU.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSearchU.setForeground(new java.awt.Color(54, 33, 89));
        jButtonSearchU.setText("Search");
        jButtonSearchU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearchU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUActionPerformed(evt);
            }
        });

        variantT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        variantT.setForeground(new java.awt.Color(54, 33, 89));
        variantT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        variantT.setText("Variant");

        Co_Brande.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Co_Brande.setForeground(new java.awt.Color(54, 33, 89));
        Co_Brande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Co_Brande.setText("Company Brande");

        rentVT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rentVT.setForeground(new java.awt.Color(54, 33, 89));
        rentVT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentVT.setText("Rent Value");

        jTextFieldType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTypeActionPerformed(evt);
            }
        });

        jTextFieldCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCOActionPerformed(evt);
            }
        });

        jTextFieldVariant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVariantActionPerformed(evt);
            }
        });

        jTextFieldUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUseActionPerformed(evt);
            }
        });

        jTextFieldRentV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRentVActionPerformed(evt);
            }
        });

        jTextFieldNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumActionPerformed(evt);
            }
        });

        useasT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        useasT.setForeground(new java.awt.Color(54, 33, 89));
        useasT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        useasT.setText("Use As");

        statusT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        statusT.setForeground(new java.awt.Color(54, 33, 89));
        statusT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusT.setText("Status");

        modelT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modelT.setForeground(new java.awt.Color(54, 33, 89));
        modelT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelT.setText("Model");

        numberT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numberT.setForeground(new java.awt.Color(54, 33, 89));
        numberT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberT.setText("Number");

        makeyearT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        makeyearT.setForeground(new java.awt.Color(54, 33, 89));
        makeyearT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        makeyearT.setText("Make Year");

        sittingCT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sittingCT.setForeground(new java.awt.Color(54, 33, 89));
        sittingCT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sittingCT.setText("Sitting Capacity");

        ingineCT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingineCT.setForeground(new java.awt.Color(54, 33, 89));
        ingineCT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingineCT.setText("Ingine Capacity");

        typeT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        typeT.setForeground(new java.awt.Color(54, 33, 89));
        typeT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeT.setText("Type");

        jButtonUpdate.setBackground(new java.awt.Color(54, 33, 89));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(54, 33, 89));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Refresh_52px_3.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(54, 33, 89));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(54, 33, 89));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trash_Can_50px_1.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simplepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jTextUpdateDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButtonSearchU, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(succes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Co_Brande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(useasT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modelT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makeyearT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sittingCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ingineCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(variantT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rentVT, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCO)
                            .addComponent(jTextFieldUse)
                            .addComponent(jTextFieldStatus)
                            .addComponent(jTextFieldModel)
                            .addComponent(jTextFieldNum)
                            .addComponent(jTextFieldMYear)
                            .addComponent(jTextFieldSitting)
                            .addComponent(jTextFieldIngine)
                            .addComponent(jTextFieldType)
                            .addComponent(jTextFieldVariant)
                            .addComponent(jTextFieldRentV, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabelFNot, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simplepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextUpdateDelete)
                    .addComponent(jButtonSearchU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFNot, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Co_Brande))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useasT)
                    .addComponent(jTextFieldUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusT)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelT)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberT)
                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeyearT))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSitting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sittingCT))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingineCT)
                    .addComponent(jTextFieldIngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeT))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(variantT))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRentV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentVT))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(succes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTypeActionPerformed

    private void jTextFieldCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCOActionPerformed

    private void jTextFieldVariantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVariantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVariantActionPerformed

    private void jTextFieldUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUseActionPerformed

    private void jTextFieldRentVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRentVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRentVActionPerformed

    private void jTextFieldNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumActionPerformed

    private void jButtonSearchUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUActionPerformed
        // TODO add your handling code here:
        if(!jTextUpdateDelete.getText().equals("")){
            Vehicle x = new Vehicle();
            Vehicle returned = x.searchVehicleByNumber(Integer.parseInt(jTextUpdateDelete.getText()));
            if(returned.getNumber()>0){
                jLabelFNot.setText("Found ..");
                setPanelData(returned);
            }else{
                jLabelFNot.setText("Not Found ..");
            }
            
        }else{
            jLabelFNot.setText("Missing Required Fields ..! Please , Complete them before Submit");
        }
    }//GEN-LAST:event_jButtonSearchUActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldCO.getText().equals("")&&!jTextFieldUse.getText().equals("")&&!jTextFieldStatus.getText().equals("")&&!jTextFieldModel.getText().equals("")&&!jTextFieldNum.getText().equals("")&&!jTextFieldMYear.getText().equals("")&&!jTextFieldSitting.getText().equals("")&&!jTextFieldIngine.getText().equals("")&&!jTextFieldType.getText().equals("")&&!jTextFieldVariant.getText().equals("")&&!jTextFieldRentV.getText().equals("")){
            Vehicle x= new Vehicle();
            x.setCompany_brande(jTextFieldCO.getText());
            x.setUse_as(jTextFieldUse.getText());
            x.setStatus(jTextFieldStatus.getText());
            x.setModel(jTextFieldModel.getText());
            x.setNumber(Integer.parseInt(jTextFieldNum.getText()));
            x.setMake_year(Integer.parseInt(jTextFieldMYear.getText()));
            x.setSitting_capacity(Integer.parseInt(jTextFieldSitting.getText()));
            x.setIngine_capacity(Integer.parseInt(jTextFieldIngine.getText()));
            x.setType(jTextFieldType.getText());
            x.setVariant(jTextFieldVariant.getText());
            x.setRent_value(Float.parseFloat(jTextFieldRentV.getText()));
            if(x.updateVehicle()){
                succes.setText("Updated Succesfully ..");
                resetPanelData();
            }else{
                succes.setText("Failed To Update ..");
            }
        }else{
            succes.setText("Missing Required Fields ..! Please , Complete them before Submit ");
        }
      
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if(!jTextUpdateDelete.getText().equals("")){
            Vehicle x= new Vehicle();
            if(x.RemoveVehicle(Integer.parseInt(jTextUpdateDelete.getText()))){
                succes.setText("Deleted Succesfully ..");
                resetPanelData();
            }else{
                succes.setText("Failed To Delete ..");
            }
        }else{
            succes.setText("Missing Required Fields ..! Please , Complete them before Submit ");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    protected void resetPanelData(){
        jTextFieldCO.setText("");
        jTextFieldUse.setText("");
        jTextFieldStatus.setText("");
        jTextFieldModel.setText("");
        jTextFieldNum.setText("");
        jTextFieldMYear.setText("");
        jTextFieldSitting.setText("");
        jTextFieldIngine.setText("");
        jTextFieldType.setText("");
        jTextFieldVariant.setText("");
        jTextFieldRentV.setText("");
    }
    protected void setPanelData(Vehicle x){
        jTextFieldCO.setText(""+x.getCompany_brande());
        jTextFieldUse.setText(""+x.getUse_as());
        jTextFieldStatus.setText(""+x.getStatus());
        jTextFieldModel.setText(""+x.getModel());
        jTextFieldNum.setText(""+x.getNumber());
        jTextFieldMYear.setText(""+x.getMake_year());
        jTextFieldSitting.setText(""+x.getSitting_capacity());
        jTextFieldIngine.setText(""+x.getIngine_capacity());
        jTextFieldType.setText(""+x.getType());
        jTextFieldVariant.setText(""+x.getVariant());
        jTextFieldRentV.setText(""+x.getRent_value());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Co_Brande;
    private javax.swing.JLabel ingineCT;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearchU;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelFNot;
    private javax.swing.JTextField jTextFieldCO;
    private javax.swing.JTextField jTextFieldIngine;
    private javax.swing.JTextField jTextFieldMYear;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldRentV;
    private javax.swing.JTextField jTextFieldSitting;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldType;
    private javax.swing.JTextField jTextFieldUse;
    private javax.swing.JTextField jTextFieldVariant;
    private javax.swing.JTextField jTextUpdateDelete;
    private javax.swing.JLabel makeyearT;
    private javax.swing.JLabel modelT;
    private javax.swing.JLabel numberT;
    private javax.swing.JLabel rentVT;
    private javax.swing.JPanel simplepanel;
    private javax.swing.JLabel sittingCT;
    private javax.swing.JLabel statusT;
    private javax.swing.JLabel succes;
    private javax.swing.JLabel typeT;
    private javax.swing.JLabel useasT;
    private javax.swing.JLabel variantT;
    // End of variables declaration//GEN-END:variables
}
