/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pl.pro.Vehicle;

/**
 *
 * @author dell
 */
public final class ViewVehicle extends javax.swing.JPanel {

    /**
     * Creates new form ViewVehicle
     */
    public ViewVehicle() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simplepanel = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        simplepanel.setBackground(new java.awt.Color(54, 33, 89));

        Add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add.setText("View A Vehicle");

        javax.swing.GroupLayout simplepanelLayout = new javax.swing.GroupLayout(simplepanel);
        simplepanel.setLayout(simplepanelLayout);
        simplepanelLayout.setHorizontalGroup(
            simplepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simplepanelLayout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(Add)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        simplepanelLayout.setVerticalGroup(
            simplepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simplepanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(Add)
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Brande", "Use As", "Status", "Model", "Number", "Make Year", "Sitting Capacity", "Ingine Capacity", "Type", "Variant", "Rent Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(simplepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simplepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addRowsTojTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[]= new Object[11];
        Vehicle veh = new Vehicle();
        ArrayList<Vehicle> vehicles = new ArrayList<>();
        vehicles = veh.listVehicles();
        for(Vehicle x: vehicles){
            rowData[0]=x.getCompany_brande();
            rowData[1]=x.getUse_as();
            rowData[2]=x.getStatus();
            rowData[3]=x.getModel();
            rowData[4]=x.getNumber();
            rowData[5]=x.getMake_year();
            rowData[6]=x.getSitting_capacity();
            rowData[7]=x.getIngine_capacity();
            rowData[8]=x.getType();
            rowData[9]=x.getVariant();
            rowData[10]=x.getRent_value();
            model.addRow(rowData);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel simplepanel;
    // End of variables declaration//GEN-END:variables
}
